name: Trigger auto deployment for image-to-3d

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/image-to-3d-AutoDeployTrigger-03c16fd2-9947-453e-b59f-5f25abd29701.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.IMAGETO3D_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IMAGETO3D_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IMAGETO3D_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.IMAGETO3D_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IMAGETO3D_REGISTRY_PASSWORD }}
          containerAppName: image-to-3d
          resourceGroup: rg-1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


